// <auto-generated />
namespace ApplicationMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrationV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationV3));
        
        string IMigrationMetadata.Id
        {
            get { return "201709211518552_migrationV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
